version: '3.8'

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: express_mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
    networks:
      - default